"""Data models for SentryAI.

Pure-stdlib dataclasses (no third-party deps) so the pipeline runs
error-free in any Python 3.9+ environment. Each model mirrors the
input/output schema defined in the SentryAI system specification.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field, asdict
from typing import Any, Dict, List, Optional


# ---------------------------------------------------------------------------
# Input models
# ---------------------------------------------------------------------------
@dataclass
class Attachment:
    filename: Optional[str] = None
    sha256: Optional[str] = None
    mime_type: Optional[str] = None

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "Attachment":
        d = d or {}
        return cls(
            filename=d.get("filename"),
            sha256=d.get("sha256"),
            mime_type=d.get("mime_type"),
        )


@dataclass
class Headers:
    from_: Optional[str] = None
    reply_to: Optional[str] = None
    subject: Optional[str] = None
    received_spf: Optional[str] = None
    dkim_result: Optional[str] = None
    dmarc_result: Optional[str] = None
    x_originating_ip: Optional[str] = None

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "Headers":
        d = d or {}
        return cls(
            from_=d.get("from"),
            reply_to=d.get("reply_to"),
            subject=d.get("subject"),
            received_spf=_norm(d.get("received_spf")),
            dkim_result=_norm(d.get("dkim_result")),
            dmarc_result=_norm(d.get("dmarc_result")),
            x_originating_ip=d.get("x_originating_ip"),
        )


@dataclass
class EmailInput:
    """Normalised representation of an inbound email submission."""

    email_id: str
    headers: Headers
    body_text: Optional[str] = None
    body_html: Optional[str] = None
    attachments: List[Attachment] = field(default_factory=list)
    urls_extracted: List[str] = field(default_factory=list)
    # True when email_id was generated by us because the input omitted it.
    email_id_autogenerated: bool = False
    # Any structural problems noticed while parsing (missing fields, etc.)
    parse_notes: List[str] = field(default_factory=list)

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "EmailInput":
        d = d or {}
        notes: List[str] = []

        email_id = d.get("email_id")
        autogen = False
        if not email_id:
            email_id = str(uuid.uuid4())
            autogen = True
            notes.append("email_id missing from input; auto-assigned a UUID.")

        if "headers" not in d or not d.get("headers"):
            notes.append("headers block missing or empty.")
        headers = Headers.from_dict(d.get("headers") or {})

        for fld in ("received_spf", "dkim_result", "dmarc_result"):
            if not (d.get("headers") or {}).get(fld):
                notes.append(f"authentication header '{fld}' missing (treated as null/none).")

        attachments = [Attachment.from_dict(a) for a in (d.get("attachments") or [])]
        urls = list(d.get("urls_extracted") or [])

        return cls(
            email_id=email_id,
            headers=headers,
            body_text=d.get("body_text"),
            body_html=d.get("body_html"),
            attachments=attachments,
            urls_extracted=urls,
            email_id_autogenerated=autogen,
            parse_notes=notes,
        )


# ---------------------------------------------------------------------------
# Output / verdict models
# ---------------------------------------------------------------------------
@dataclass
class ContentSignal:
    signal_type: str  # urgency|credential_harvest|impersonation|evasion|prompt_injection|other
    description: str
    points_contributed: int


@dataclass
class IOCResult:
    ioc_type: str  # ip|url|domain|hash|email
    value: str
    sources_queried: List[str] = field(default_factory=list)
    verdict: str = "unknown"  # malicious|suspicious|clean|unknown
    detail: str = ""
    points_contributed: int = 0
    # Raw per-source payloads, retained for transparency/debugging.
    raw: Dict[str, Any] = field(default_factory=dict)


@dataclass
class MitreTechnique:
    technique_id: str
    technique_name: str
    tactic: str
    relevance: str


@dataclass
class HeaderAuthSignals:
    spf: Optional[str]
    dkim: Optional[str]
    dmarc: Optional[str]
    from_reply_to_mismatch: bool
    points_contributed: int


@dataclass
class Verdict:
    email_id: str
    verdict: str  # BENIGN|SUSPICIOUS|PHISHING
    confidence: str  # high|medium|low
    risk_score: int
    prompt_injection_detected: bool
    human_review_recommended: bool
    classification_reasoning: str
    header_authentication: HeaderAuthSignals
    content_signals: List[ContentSignal]
    ioc_enrichment: List[IOCResult]
    mitre_attack: List[MitreTechnique]
    recommended_actions: List[str]
    stages_completed: List[str]
    tools_called: List[str]
    ioc_count: int
    processing_notes: str

    def to_dict(self) -> Dict[str, Any]:
        """Render the strict output JSON schema."""
        return {
            "email_id": self.email_id,
            "verdict": self.verdict,
            "confidence": self.confidence,
            "risk_score": self.risk_score,
            "prompt_injection_detected": self.prompt_injection_detected,
            "human_review_recommended": self.human_review_recommended,
            "classification_reasoning": self.classification_reasoning,
            "signals": {
                "header_authentication": {
                    "spf": self.header_authentication.spf,
                    "dkim": self.header_authentication.dkim,
                    "dmarc": self.header_authentication.dmarc,
                    "from_reply_to_mismatch": self.header_authentication.from_reply_to_mismatch,
                    "points_contributed": self.header_authentication.points_contributed,
                },
                "content_signals": [asdict(s) for s in self.content_signals],
                "ioc_enrichment": [
                    {
                        "ioc_type": i.ioc_type,
                        "value": i.value,
                        "sources_queried": i.sources_queried,
                        "verdict": i.verdict,
                        "detail": i.detail,
                        "points_contributed": i.points_contributed,
                    }
                    for i in self.ioc_enrichment
                ],
            },
            "mitre_attack": [asdict(m) for m in self.mitre_attack],
            "recommended_actions": self.recommended_actions,
            "analysis_metadata": {
                "stages_completed": self.stages_completed,
                "tools_called": self.tools_called,
                "ioc_count": self.ioc_count,
                "processing_notes": self.processing_notes,
            },
        }


def _norm(v: Optional[str]) -> Optional[str]:
    """Lower-case and strip authentication result strings."""
    if v is None:
        return None
    return str(v).strip().lower() or None
