"""Pipeline orchestrator — SentryAI.

Wires the six analysis stages together and exposes two public functions:

    analyze(email_input, enricher=None) -> dict
    analyze_batch(emails, enricher=None) -> list[dict]

Stage execution order
=====================
  1. header_auth  — analyze_headers  -> (HeaderAuthSignals, ips_to_enrich)
  2. content      — analyze_content  -> (content_signals, injection_detected,
                                          injection_categories)
  3. ioc_enrichment — extract_iocs, merge IPs, enrich_iocs
  4. rag_retrieval  — map_techniques (MITRE ATT&CK mapping)
  5. scoring        — total_score + classify
  6. verdict        — build_verdict

All email content is treated as UNTRUSTED DATA. Instructions embedded in
the email body are never executed; the pipeline operates only on
structured outputs from each stage.
"""

from __future__ import annotations

from copy import deepcopy
from typing import Any, Dict, List, Optional, Union

from sentryai import enrichment as _enr
from sentryai.models import EmailInput
from sentryai.validation import validate_email, collection, budget, MAX_BATCH, DEFAULT_LOOKUP_CALLS, MAX_IOCS
from sentryai.stage4_mitre import map_techniques
from sentryai.stage5_scoring import classify, total_score
from sentryai.stage6_verdict import build_verdict

# Sibling modules (written by parallel agents). They may not be present on
# disk during isolated testing; import them at runtime so import errors are
# deferred to actual call time rather than module load time.
try:
    from sentryai.stage1_headers import analyze_headers as _analyze_headers
    _STAGE1_AVAILABLE = True
except ImportError:
    _STAGE1_AVAILABLE = False

try:
    from sentryai.stage2_content import analyze_content as _analyze_content
    _STAGE2_AVAILABLE = True
except ImportError:
    _STAGE2_AVAILABLE = False

try:
    from sentryai.stage3_iocs import (
        extract_iocs as _extract_iocs,
        enrich_iocs as _enrich_iocs,
    )
    _STAGE3_AVAILABLE = True
except ImportError:
    _STAGE3_AVAILABLE = False

# Sentinel strings for stage tracking.
_STAGES = ["header_auth", "content", "ioc_enrichment", "rag_retrieval", "scoring"]

# Maximum characters of body_text / body_html we will scan. Untrusted email
# can be arbitrarily large; scanning multi-MB bodies with every regex is a
# resource-exhaustion vector (code-review #8). Beyond this we truncate and
# note it — the leading content is more than enough for signal detection.
_MAX_BODY_CHARS = 200_000


def _guard_body_size(email: EmailInput, extra_notes: List[str]) -> None:
    """Truncate oversized bodies in place and record a processing note."""
    for attr in ("body_text", "body_html"):
        val = getattr(email, attr)
        if val and len(val) > _MAX_BODY_CHARS:
            setattr(email, attr, val[:_MAX_BODY_CHARS])
            extra_notes.append(
                f"{attr} exceeded {_MAX_BODY_CHARS} chars and was truncated "
                f"for analysis (original length {len(val)})."
            )


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _ensure_email(email_input: Union[Dict[str, Any], EmailInput]) -> EmailInput:
    """Return an EmailInput, parsing a dict if necessary."""
    if isinstance(email_input, EmailInput):
        from dataclasses import asdict
        data = asdict(email_input)
        from sentryai.validation import mapping
        headers = mapping(data["headers"], "headers")
        headers["from"] = headers.pop("from_", None)
        validate_email(data)
        return email_input
    return EmailInput.from_dict(email_input)


def _make_enricher(enricher: Optional[_enr.Enricher]) -> _enr.Enricher:
    """Return the supplied enricher, or a fresh StubEnricher as default."""
    if enricher is not None:
        return enricher
    return _enr.StubEnricher()


def _stub_header_analysis(email: EmailInput):
    """Fallback when Stage 1 module is not available."""
    from sentryai.models import HeaderAuthSignals
    notes_extra = "stage1_headers module unavailable; header analysis skipped."
    signals = HeaderAuthSignals(
        spf=email.headers.received_spf,
        dkim=email.headers.dkim_result,
        dmarc=email.headers.dmarc_result,
        from_reply_to_mismatch=False,
        points_contributed=0,
    )
    return signals, []


def _stub_content_analysis(email: EmailInput):
    """Fallback when Stage 2 module is not available."""
    return [], False, []


def _build_processing_notes(
    email: EmailInput,
    ioc_notes: List[str],
    extra_notes: List[str],
) -> str:
    """Combine all processing notes into a single string."""
    all_notes: List[str] = list(email.parse_notes)
    if email.email_id_autogenerated:
        # parse_notes already includes this message from models.py, but guard
        # in case that implementation changes.
        if not any("auto-assigned" in n for n in all_notes):
            all_notes.append("email_id was auto-assigned a UUID (missing from input).")
    all_notes.extend(ioc_notes)
    all_notes.extend(extra_notes)
    return " | ".join(all_notes) if all_notes else "No anomalies noted."


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def analyze(
    email_input: Union[Dict[str, Any], EmailInput],
    enricher: Optional[_enr.Enricher] = None,
    trust_missing_auth: bool = False,
    max_url_lookups: Optional[int] = None,
    trusted_auth_results: bool = False,
    max_lookup_calls: int = DEFAULT_LOOKUP_CALLS,
) -> Dict[str, Any]:
    """Run the full six-stage analysis pipeline on a single email.

    Args:
        email_input: Either a raw dict (will be parsed via
                     ``EmailInput.from_dict``) or an ``EmailInput``
                     instance.
        trusted_auth_results: Accept normalized auth only from a separately
                     trusted mail verifier; never authorize raw header claims.
        max_lookup_calls: Total provider calls including retries, per email
                     (default 100; range 0..1000).
        enricher:    An ``Enricher`` instance for IOC reputation lookups.
                     Defaults to ``StubEnricher`` (offline, deterministic).

    Returns:
        The verdict as a plain dict (``Verdict.to_dict()``).

    Raises:
        Any unhandled exception from a stage propagates to the caller.
        Use ``analyze_batch`` for fault-isolated batch processing.
    """
    from sentryai.validation import InputValidationError
    if type(trusted_auth_results) is not bool or type(trust_missing_auth) is not bool:
        raise InputValidationError("Authentication trust options must be booleans")
    email = deepcopy(_ensure_email(email_input))
    budget(max_lookup_calls, "max_lookup_calls")
    if max_url_lookups is not None:
        budget(max_url_lookups, "max_url_lookups")
    enricher = _enr.BudgetEnricher(_make_enricher(enricher), max_lookup_calls)
    extra_notes: List[str] = []

    # Cap untrusted body size before any regex scanning (resource guard).
    _guard_body_size(email, extra_notes)

    # ------------------------------------------------------------------
    # Stage 1: Header authentication
    # ------------------------------------------------------------------
    if _STAGE1_AVAILABLE:
        header_signals, ips_to_enrich = _analyze_headers(
            email, trust_missing_auth=trust_missing_auth, trusted_auth_results=trusted_auth_results
        )
        if trust_missing_auth and any(
            v is None for v in (email.headers.received_spf,
                                email.headers.dkim_result,
                                email.headers.dmarc_result)
        ):
            extra_notes.append(
                "Missing SPF/DKIM/DMARC treated as neutral (trust_missing_auth)."
            )
    else:
        header_signals, ips_to_enrich = _stub_header_analysis(email)
        extra_notes.append("stage1_headers module unavailable; header analysis skipped.")

    if not trusted_auth_results and any(v is not None for v in (
            email.headers.received_spf, email.headers.dkim_result, email.headers.dmarc_result)):
        extra_notes.append("Unverified authentication claims ignored; use only results from a trusted verifier.")

    # ------------------------------------------------------------------
    # Stage 2: Content analysis
    # ------------------------------------------------------------------
    if _STAGE2_AVAILABLE:
        content_signals, injection_detected, injection_categories = _analyze_content(email)
    else:
        content_signals, injection_detected, injection_categories = _stub_content_analysis(email)
        extra_notes.append("stage2_content module unavailable; content analysis skipped.")

    # ------------------------------------------------------------------
    # Stage 3: IOC extraction and enrichment
    # ------------------------------------------------------------------
    ioc_notes: List[str] = []

    if _STAGE3_AVAILABLE:
        raw_iocs = _extract_iocs(email)

        # Merge any IPs surfaced by Stage 1 into the IOC dict.
        if ips_to_enrich:
            existing_ips: List[str] = list(raw_iocs.get("ips") or [])
            for ip in ips_to_enrich:
                if ip not in existing_ips:
                    existing_ips.append(ip)
            raw_iocs["ips"] = existing_ips

        # Bound retained IOCs and all provider calls (including retries).
        remaining = MAX_IOCS
        for kind, values in raw_iocs.items():
            if len(values) > remaining:
                extra_notes.append("IOC limit reached; extraction analysis incomplete.")
            bounded = values[:remaining]
            if any(len(value) > 4096 for value in bounded):
                extra_notes.append("Oversized extracted indicator skipped; analysis incomplete.")
            raw_iocs[kind] = [value for value in bounded if len(value) <= 4096]
            remaining -= len(raw_iocs[kind])
        ioc_results, ioc_notes = _enrich_iocs(raw_iocs, enricher, max_url_lookups=max_url_lookups)
    else:
        ioc_results = []
        ioc_notes = ["stage3_iocs module unavailable; IOC enrichment skipped."]

    if enricher.exhausted:
        extra_notes.append(f"Provider call budget ({max_lookup_calls}) exhausted; analysis incomplete.")

    # ------------------------------------------------------------------
    # Stage 4: MITRE ATT&CK mapping (RAG retrieval)
    # ------------------------------------------------------------------
    attachments_present = bool(email.attachments)
    mitre = map_techniques(
        content_signals=content_signals,
        ioc_results=ioc_results,
        prompt_injection_detected=injection_detected,
        attachments_present=attachments_present,
    )

    # ------------------------------------------------------------------
    # Stage 5: Scoring and classification
    # ------------------------------------------------------------------
    score = total_score(
        header_points=header_signals.points_contributed,
        content_signals=content_signals,
        ioc_results=ioc_results,
    )

    any_ioc_malicious = any(
        i.verdict.lower() == "malicious" for i in ioc_results
    )
    verdict_label, confidence, human_review = classify(
        score=score,
        any_ioc_malicious=any_ioc_malicious,
        injection_detected=injection_detected,
    )

    # Degraded-enrichment guard (code-review #9): if IOC lookups failed, the
    # verdict rests on incomplete infrastructure data, so lower confidence to
    # "low". NOTE: "low" reflects DATA COMPLETENESS, not verdict strength — a
    # PHISHING verdict driven by strong content/header signals can still be
    # reported with low confidence when threat-intel enrichment was incomplete
    # (code-review D).
    analysis_incomplete = bool(ioc_notes) or any(
        "truncated" in n or "incomplete" in n or "Unverified" in n or "unavailable" in n for n in extra_notes)
    if any(v is None for v in (header_signals.spf, header_signals.dkim, header_signals.dmarc)):
        analysis_incomplete = True
        extra_notes.append("Authentication evidence incomplete; missing results are not verified passes.")
    if analysis_incomplete:
        confidence = "low"
        human_review = True
        extra_notes.append(
            "Confidence downgraded to low: analysis was incomplete; "
            "manual review is required."
        )

    # ------------------------------------------------------------------
    # Stage 6: Verdict assembly
    # ------------------------------------------------------------------
    # Collect all tool names: enricher tools + pipeline-level logical tools.
    tools_called: List[str] = list(enricher.tools_called)
    if "rag_retrieve" not in tools_called:
        tools_called.append("rag_retrieve")

    stages_completed = list(_STAGES)

    processing_notes = _build_processing_notes(email, ioc_notes, extra_notes)

    verdict = build_verdict(
        email=email,
        header_signals=header_signals,
        content_signals=content_signals,
        ioc_results=ioc_results,
        mitre=mitre,
        score=score,
        verdict_label=verdict_label,
        confidence=confidence,
        human_review=human_review,
        injection_detected=injection_detected,
        stages_completed=stages_completed,
        tools_called=tools_called,
        processing_notes=processing_notes,
    )

    return verdict.to_dict()


def analyze_batch(
    emails: List[Union[Dict[str, Any], EmailInput]],
    enricher: Optional[_enr.Enricher] = None,
    trust_missing_auth: bool = False,
    max_url_lookups: Optional[int] = None,
    trusted_auth_results: bool = False,
    max_lookup_calls: int = DEFAULT_LOOKUP_CALLS,
) -> List[Dict[str, Any]]:
    """Run the pipeline on a list of emails, returning one verdict per email.

    Each email is processed INDEPENDENTLY:
    * If ``enricher`` is None, a fresh ``StubEnricher`` is created for each
      email so that ``tools_called`` state does not leak between emails.
    * A supplied provider is shared, but call budgets and verdict tool metadata
      are isolated per email.

    A failure in one email does not abort the batch. On exception the
    corresponding list entry contains a minimal error verdict dict with
    ``processing_notes`` describing the error.

    Args:
        emails:   A list of raw dicts or ``EmailInput`` instances.
        enricher: Optional shared enricher. When None, a fresh
                  ``StubEnricher`` is used per email.

    Returns:
        A list of verdict dicts in the same order as ``emails``.
    """
    collection(emails, "batch", MAX_BATCH)
    budget(max_lookup_calls, "max_lookup_calls")
    results: List[Dict[str, Any]] = []

    for idx, email_input in enumerate(emails):
        # Provider may be shared; analyze creates a fresh budget and tool
        # metadata wrapper for each email.
        per_email_enricher = enricher if enricher is not None else _enr.StubEnricher()

        try:
            result = analyze(email_input, enricher=per_email_enricher,
                             trust_missing_auth=trust_missing_auth,
                             max_url_lookups=max_url_lookups,
                             trusted_auth_results=trusted_auth_results, max_lookup_calls=max_lookup_calls)
        except Exception as exc:  # pylint: disable=broad-except
            # Attempt to extract an email_id for the error record.
            try:
                email_obj = _ensure_email(email_input)
                email_id = email_obj.email_id
            except Exception:
                email_id = f"batch-item-{idx}"

            result = {
                "email_id": email_id,
                "verdict": "ERROR",
                "confidence": "none",
                "risk_score": 0,
                "prompt_injection_detected": False,
                "human_review_recommended": True,
                "classification_reasoning": (
                    "Pipeline error: analysis could not be completed for this email."
                ),
                "signals": {
                    "header_authentication": {},
                    "content_signals": [],
                    "ioc_enrichment": [],
                },
                "mitre_attack": [],
                "recommended_actions": [
                    "Manual review required: pipeline raised an exception for this email.",
                ],
                "analysis_metadata": {
                    "stages_completed": [],
                    "tools_called": [],
                    "ioc_count": 0,
                    "processing_notes": (
                        f"Pipeline exception at batch index {idx}: "
                        f"{type(exc).__name__}: analysis failed; manual review required."
                    ),
                },
            }

        results.append(result)

    return results
